apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    role: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      role: myapp
      tier: web
  template:
    metadata:
      labels:
        role: myapp
        tier: web
    spec:
      containers:
      - name: myapp
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

