apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: network-zone-dmz
  namespace: openshift-ingress-operator
spec:
  domain: apps.ocp.dmz.dominio.com
  namespaceSelector:
    matchLabels:
      network-zone: dmz
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: dmz
  replicas: 3